/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * 默认模块
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  username?: string;
  email?: string;
  password?: string;
  confirmPassword?: string;
}
