/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * 默认模块
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponse } from './loginResponse';

export interface ResultLoginResponse {
  code?: number;
  message?: string;
  data?: LoginResponse;
  /** 填充当前时间戳 */
  timestamp?: number;
}
