/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * 默认模块
 * OpenAPI spec version: 1.0.0
 */

/**
 * 此 token 对应的 LoginId，未登录时为 null
 */
export type SaTokenInfoLoginId = { [key: string]: unknown };
