/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * 默认模块
 * OpenAPI spec version: 1.0.0
 */
export interface UserProfile {
  id?: number;
  username?: string;
  email?: string;
}

export interface ResultUserProfile {
  code?: number;
  message?: string;
  data?: UserProfile;
  /** 填充当前时间戳 */
  timestamp?: number;
}

export interface RegisterRequest {
  username?: string;
  email?: string;
  password?: string;
  confirmPassword?: string;
}

/**
 * 此 token 对应的 LoginId，未登录时为 null
 */
export type SaTokenInfoLoginId = { [key: string]: unknown };

export interface SaTokenInfo {
  /** token 名称 */
  tokenName?: string;
  /** token 值 */
  tokenValue?: string;
  /** 此 token 是否已经登录 */
  isLogin?: boolean;
  /** 此 token 对应的 LoginId，未登录时为 null */
  loginId?: SaTokenInfoLoginId;
  /** 多账号体系下的账号类型 */
  loginType?: string;
  /** token 剩余有效期（单位: 秒） */
  tokenTimeout?: number;
  /** Account-Session 剩余有效时间（单位: 秒） */
  sessionTimeout?: number;
  /** Token-Session 剩余有效时间（单位: 秒） */
  tokenSessionTimeout?: number;
  /** token 距离被冻结还剩多少时间（单位: 秒） */
  tokenActiveTimeout?: number;
  /** 登录设备类型 */
  loginDeviceType?: string;
  /** 自定义数据（暂无意义，留作扩展） */
  tag?: string;
}

export interface LoginResponse {
  tokenInfo?: SaTokenInfo;
  user?: UserProfile;
}

export interface ResultLoginResponse {
  code?: number;
  message?: string;
  data?: LoginResponse;
  /** 填充当前时间戳 */
  timestamp?: number;
}

export interface LoginRequest {
  account?: string;
  password?: string;
}

