/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * 默认模块
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ResultLoginResponse,
  ResultUserProfile
} from '../../model';


export const getPostApiAuthRegisterResponseMock = (overrideResponse: Partial<Extract<ResultUserProfile, object>> = {}): ResultUserProfile => ({code: faker.helpers.arrayElement([faker.number.int(), undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), data: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.number.int(), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), timestamp: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})

export const getPostApiAuthLoginResponseMock = (overrideResponse: Partial<Extract<ResultLoginResponse, object>> = {}): ResultLoginResponse => ({code: faker.helpers.arrayElement([faker.number.int(), undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), data: faker.helpers.arrayElement([{tokenInfo: faker.helpers.arrayElement([{tokenName: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), tokenValue: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), isLogin: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), loginId: faker.helpers.arrayElement([{}, undefined]), loginType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), tokenTimeout: faker.helpers.arrayElement([faker.number.int(), undefined]), sessionTimeout: faker.helpers.arrayElement([faker.number.int(), undefined]), tokenSessionTimeout: faker.helpers.arrayElement([faker.number.int(), undefined]), tokenActiveTimeout: faker.helpers.arrayElement([faker.number.int(), undefined]), loginDeviceType: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), tag: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined]), user: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.number.int(), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), email: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])}, undefined])}, undefined]), timestamp: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse})


export const getPostApiAuthRegisterMockHandler = (overrideResponse?: ResultUserProfile | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ResultUserProfile> | ResultUserProfile), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/register', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiAuthRegisterResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiAuthLoginMockHandler = (overrideResponse?: ResultLoginResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ResultLoginResponse> | ResultLoginResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiAuthLoginResponseMock(),
      { status: 200
      })
  }, options)
}
export const getDefaultMock = () => [
  getPostApiAuthRegisterMockHandler(),
  getPostApiAuthLoginMockHandler()]
