/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * 默认模块
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  RegisterRequest,
  ResultLoginResponse,
  ResultUserProfile
} from '../../model';




  export const getDefault = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * 创建新用户账号并返回用户基础信息。
 * @summary 用户注册
 */
const postApiAuthRegister = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ResultUserProfile>> => {
    return axiosInstance.post(
      `/api/auth/register`,
      registerRequest,options
    );
  }
/**
 * 使用账号与密码进行身份认证，认证通过后签发登录 Token。
 * @summary 用户登录
 */
const postApiAuthLogin = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ResultLoginResponse>> => {
    return axiosInstance.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }
return {}};
